resources:
  jobs:
    train_classifier_a:
      name: "train_classifier_a"
      parameters:
        - name: catalog
          default: ${var.catalog}
        - name: schema
          default: ${resources.schemas.default.name}
        - name: experiment_name
          default: ${var.classifier_experiment_name}
        - name: registered_model_suffix
          default: ${var.classifier_experiment_name}
      environments:
        - environment_key: classifier_train_env
          spec:
            environment_version: "5"
            dependencies:
              - ../dist/*.whl
      tasks:
        - task_key: train_classifier_a
          environment_key: classifier_train_env
          notebook_task:
            notebook_path: ../src/jobs/train_classifier_a.ipynb
            base_parameters:
              catalog: "{{job.parameters.catalog}}"
              schema: "{{job.parameters.schema}}"
              experiment_name: "{{job.parameters.experiment_name}}"
              registered_model_suffix: "{{job.parameters.registered_model_suffix}}"
